# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: smart-api
# spec:
#   replicas: 3
#   selector:
#     matchLabels:
#       app: smart-api
#   template:
#     metadata:
#       labels:
#         app: smart-api
#     spec:
#       containers:
#       - name: smart-api
#         image: smart-tasks:latest
#         ports:
#         - containerPort: 1050
#         env:
#           - name: PORT
#             value: "1050"
apiVersion: apps/v1
kind: Deployment
metadata:
  name: smart-api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: smart-api
  template:
    metadata:
      labels:
        app: smart-api
    spec:
      containers:
      - name: smart-api
        image: smart-tasks:latest
        ports:
        - containerPort: 1050
        env:
          - name: PORT
            value: "1050"
        resources:
          requests:
            memory: "256Mi"
            cpu: "500m"
          limits:
            memory: "512Mi"
            cpu: "1"
